// English skeleton of the help drawer; same paths as zh-TW
import type { HelpPage } from './types'

const p = (path: string, title: string, what: string[], how: string[], faq: { q: string; a: string }[], related: { to: string; label: string }[]): HelpPage => ({ path, title, what, how, faq, related })

export const pagesEn: HelpPage[] = [
  p('/today', 'Today', ['Home. Three questions: what needs my decision, what went wrong, what did it cost; plus what got done today.', 'A quiet day shows an empty page.'], ['Approve or reject inline; same data as the inbox.', 'Click a failed flow to see which step broke.', 'Amber text means a guardrail is near its cap.', 'Refreshes every 30 seconds.'], [{ q: 'Where are the details?', a: 'Settings → Usage for 30 days; Limits for daily caps.' }], [{ to: '/inbox', label: 'Inbox' }, { to: '/workflows', label: 'Flows' }]),
  p('/workbench', 'Workbench', ['Chat with one agent.', 'Sessions on the left, messages and composer on the right.'], ['Pick an agent top-left.', 'Press “+ New session”, type a task, Enter.', 'Stop or steer while streaming.', 'Approve or deny dangerous commands when asked.', 'Ctrl/⌘+K searches all sessions.'], [{ q: 'My profile is missing?', a: 'Enable it on the Agents page; only default is enabled at first.' }, { q: 'Where is history stored?', a: 'In Studio’s DB; Hermes history is under the “Hermes” group and must be imported.' }], [{ to: '/agents', label: 'Agents' }, { to: '/inbox', label: 'Inbox' }]),
  p('/agents', 'Agents', ['Each Hermes profile maps to one agent.', 'Name/title are for colleagues; SOUL.md is the persona.'], ['Enable the profile.', 'Fill name and title, save.', 'Edit SOUL.md; applies on next run.', 'Use “History” to diff and roll back.'], [{ q: 'How to add an agent?', a: 'Create a profile on the Profiles page.' }, { q: 'Shared memory?', a: 'Yes, Hermes keeps one memory per profile.' }], [{ to: '/profiles', label: 'Profiles' }, { to: '/models', label: 'Models' }]),
  p('/profiles', 'Profiles', ['A profile is an isolated Hermes identity.', 'Create, clone, delete; assign profiles to accounts.'], ['Create with a name.', 'Optionally clone an existing profile.', 'Enable it on Agents.', 'Assign to members under account binding.'], [{ q: 'Delete removes files?', a: 'Yes, ~/.hermes/profiles/<p> is removed.' }], [{ to: '/agents', label: 'Agents' }]),
  p('/models', 'Models', ['Which brain each staff member uses; keys stay on the server.', 'Providers are discovered automatically; this page only picks models.'], ['Pick a staff member.', 'Press ★ on a model to make it the default.', 'Per-conversation override is in the chat header.', 'Turn on engineer mode to add your own provider.'], [{ q: 'Provider missing?', a: 'No key yet; fill it in engineer mode or ask an engineer.' }], [{ to: '/usage', label: 'Usage' }]),
  p('/skills', 'Skills & Memory', ['What each staff member can do and remembers: skills, bundles, memory files, relationship graph.'], ['Pick a staff member.', 'Toggle skills or write notes.', 'Edit memory files; applies on the next conversation.'], [{ q: 'Disable deletes files?', a: 'No, only flagged.' }], [{ to: '/agents', label: 'Agents' }]),
  p('/bots', 'Bots (messenger)', ['Talk to bots like a messaging app: one DM per bot, or put 2–6 bots in a group.', 'Documents a bot produces show up as cards; other bots can revise them and every version is kept.'], ['“+” → “New bot” (Alt+N): pick a suggested role or write your own.', '“+” → “New group”: pick 2–6 bots. Without @ the bots decide who answers; @name to assign, @everyone for all.', 'Hover a message to reply, react or start a thread; the send button turns into Stop while bots work.', 'Open a doc card on the right to read, edit, compare versions, or ask a bot to revise it.', '⌘K switches chats and searches messages and docs.'], [{ q: 'Does deleting a bot delete its Hermes profile?', a: 'No. Its DM and group memberships go; the profile and documents stay.' }], [{ to: '/groupchat', label: 'Group chat (classic)' }, { to: '/docs', label: 'Docs' }]),
  p('/groupchat', 'Group chat', ['Open a room and pull in two or more staff members; invite colleagues too.', '@name picks who answers.'], ['Press “+ New room”, pick staff and the no-mention rule.', 'Type “@name question”.', 'Compress when messages pile up.', 'Colleagues join via “Have an invite code?”.'], [{ q: 'Staff do not talk to each other?', a: 'Un-mentioned AI messages never trigger others; depth limit is 3.' }], [{ to: '/workbench', label: 'Workbench' }]),
  p('/workflows', 'Flows', ['A flow is a chain of hand-offs: who, what, to whom, where it stops for you, when it runs, where the result goes.', 'One card per flow: participants, last run, next run, and a Run once button.'], ['Press "+ New flow" and describe the job in one sentence (or pick a template).', 'Opening a flow lands on "Last run": one line per step with who, what, how long, and the first line of output; a step waiting for you shows OK / Send back inline.', 'Switch to "How it runs" to edit: steps are collapsed to one line, click a line to expand who / what. Hover between lines for "+ Insert a step here"; drag the handle to reorder.', '"+ Add a step" has three moves: ask staff, wait for me, send out. Picking a coding staff member turns the step into a code run.', '"When it runs" and "Spend at most" sit in the bar at the bottom of "How it runs".', 'Branches, loops, the canvas, step replay and self-check appear only in engineer mode.'], [{ q: 'Where is Save?', a: 'It saves about a second after you stop typing; the top bar goes from Saving... back to Saved.' }, { q: 'Only one step expands?', a: 'Yes; shift-click keeps others open.' }, { q: 'Cannot reorder?', a: 'Reordering is locked when the flow branches or loops; edit it on the canvas (engineer mode).' }, { q: 'Over limit on step 2?', a: 'Spend at most is too small; start tokens at 200000.' }, { q: 'LINE delivery fails?', a: 'Configure the LINE channel first.' }], [{ to: '/today', label: 'Today' }, { to: '/inbox', label: 'Inbox' }, { to: '/limits', label: 'Limits' }]),
  p('/workflows/approvals', 'Waiting for me', ['Every step across your flows that stopped for you.', 'Today and the inbox are the usual way in; this page is a fallback.'], ['Expand an item.', 'OK with a comment, or send back.'], [{ q: 'vs Inbox?', a: 'Inbox merges all decision types.' }], [{ to: '/workflows', label: 'Flows' }]),
  p('/workflows/runs', 'Step replay', ['Engineer mode: step-by-step replay of one run.'], ['Drag the slider.', 'Click a node for its conversation.', 'Run again from a node.'], [{ q: 'Why skipped?', a: 'Over limit or condition false.' }], [{ to: '/workflows', label: 'Flows' }]),
  p('/kanban', 'Kanban', ['Task board for your staff: to do → ready → running → review → blocked → done.', 'Drag to move; Dispatch hands a card to a staff member.'], ['Create a card.', 'Drag between columns (not into Running).', 'Open a card and press Dispatch.'], [{ q: 'Yellow banner?', a: 'Health check results, e.g. a card stuck too long.' }], [{ to: '/inbox', label: 'Inbox' }]),
  p('/coding', 'Coding staff', ['Install, configure and run Claude Code / Codex / Pi.'], ['Install if missing.', 'Configure workspace, model, API mode, budget.', 'New conversation, type a task, run.', 'Check the diff tab.'], [{ q: 'No budget in proxy mode?', a: 'Claude Code would misprice; omitted on purpose.' }], [{ to: '/workflows', label: 'Flows' }]),
  p('/inbox', 'Inbox', ['Everything needing a human decision.', 'Handled items disappear.'], ['Filter by kind.', 'Approve/reject gates inline.', 'Open others, then mark done.'], [{ q: 'Count not updating?', a: 'Fetched on mount; refresh.' }], [{ to: '/workflows/approvals', label: 'Waiting for me' }]),
  p('/events', 'Events', ['Immutable timeline of everything that entered the hub.'], ['Filter by source/kind/agent.', 'Change the date range.', 'Export CSV.'], [{ q: 'Empty?', a: 'Widen the range or run a chat.' }], [{ to: '/inbox', label: 'Inbox' }]),
  p('/channels', 'Connect LINE and other platforms', ['Connect staff to LINE, Telegram, Discord, Slack.', 'Secrets stay on the server.'], ['Check the connection status on top.', 'Follow the three LINE steps: create an Official Account, paste the token, paste the URL shown here into LINE.', 'Save and reconnect.'], [{ q: 'Public URL?', a: 'An https URL reaching this machine; ask an engineer for a tunnel, or deliver elsewhere for now.' }], [{ to: '/settings', label: 'Settings' }]),
  p('/cron', 'Cron', ['Hermes scheduled jobs via gateway.'], ['Create with a 5-field cron.', 'Pick profile, prompt, delivery.', 'Pause, resume, run now.'], [{ q: 'Timezone?', a: 'Server local time.' }], [{ to: '/workflows', label: 'Flows' }]),
  p('/files', 'Files', ['Browse local Hermes workspace, profiles, uploads.'], ['Switch root.', 'Open folders.', 'Edit text files.', 'Attach to chat.'], [{ q: 'Docker/SSH?', a: 'Local filesystem only.' }], [{ to: '/workbench', label: 'Workbench' }]),
  p('/usage', 'Usage', ['30-day tokens, cost and cache hit rate from Hermes state.db.'], ['Pick a range.', 'Filter to Studio-only.', 'Set price 0 for subscription models.'], [{ q: 'Differs from bill?', a: 'Estimated from a price table.' }], [{ to: '/limits', label: 'Limits' }]),
  p('/limits', 'Cost guardrails', ['Daily token/USD limits per company or agent.'], ['Pick scope.', 'Set limits.', 'Choose disable or notify.', 'Save; resets daily.'], [{ q: 'Re-enable?', a: 'On the Agents page or next day.' }], [{ to: '/usage', label: 'Usage' }]),
  p('/soul-history', 'SOUL history', ['Every SOUL.md write through Studio is versioned.'], ['Pick a profile.', 'Diff two versions.', 'Roll back.'], [{ q: 'External edits?', a: 'Not versioned.' }], [{ to: '/agents', label: 'Agents' }]),
  p('/theme', 'Theme', ['Light/dark, style, font size, colors; synced to your account.'], ['Pick a mode.', 'Adjust.', 'Reset.'], [{ q: 'Top bar toggle?', a: 'Same setting.' }], [{ to: '/settings', label: 'Hermes status' }]),
  p('/logs', 'Logs', ['Hermes, profile and Studio logs with filters and follow.'], ['Pick a file.', 'Filter.', 'Follow.'], [{ q: 'Which first?', a: 'Gateway log for chat issues; Studio log for 500s.' }], [{ to: '/events', label: 'Events' }]),
  p('/voice', 'Voice', ['Browser speech first; whisper.cpp / edge-tts fallback.'], ['Test mic.', 'Test TTS.', 'Install fallbacks if needed.'], [{ q: 'edge-tts not bundled?', a: 'GPL-3.0.' }], [{ to: '/groupchat', label: 'Group chat' }]),
  p('/admin', 'Admin', ['Terminal, MCP servers, plugins, versions.'], ['Terminal tab.', 'MCP tab.', 'Plugins tab.', 'Version tab.'], [{ q: 'First login?', a: 'Change the admin password.' }], [{ to: '/settings', label: 'Hermes status' }]),
  p('/search', 'Search', ['One box searches chats, group rooms, workflow outputs and events (FTS5, CJK aware).'], ['Type a keyword.', 'Narrow by scope, time or agent.', 'Give agents the same search: `myhermescompany install-skill mhc-search --profile <p>`.'], [{ q: 'Fresh message missing?', a: 'The index syncs every few seconds.' }], [{ to: '/events', label: 'Events' }]),
  p('/compat', 'Hermes compatibility', ['Every Hermes touch point is a contract item checked against the real Hermes.', 'Verdict: compatible / partial / incompatible, with affected modules.'], ['Run “Check now” (read-only, ~1 min).', 'Before upgrading, run “Precheck” for a version: sandbox install, never touches ~/.hermes.', 'CLI: `myhermescompany hermes-check`, `myhermescompany precheck <tag>`.'], [{ q: 'Is “partial” usable?', a: 'Yes; only critical failures mean incompatible.' }], [{ to: '/settings', label: 'Hermes status' }]),
  p('/doc-mode', 'Doc mode', ['A conversation exists to finish one document; every turn rewrites the whole document.', 'Document in the middle, chat on the right.'], ['Press “Create the first document” when there are none.', 'Pick a document, start the conversation.', 'Review the new version and its diff; accept or revert.', 'Edit by hand to create your own version.', 'Hover a document in the left list for Archive / Delete.'], [{ q: 'Where is it stored?', a: 'Versions in the DB; the latest is written to a .md in the workspace.' }, { q: 'Edited the file myself?', a: 'The panel flags drift; snapshot it as a new version.' }], [{ to: '/docs', label: 'Documents' }, { to: '/workbench', label: 'Workbench' }]),
  p('/docs', 'Documents', ['Every document with status, stage, origin and current version.', 'Detail page shows the body, version history and the lineage graph.'], ['Filter by status/origin/stage or search.', 'Open a document.', 'Compare any two versions or revert.', 'Click a lineage node to jump there.', 'Each row has Archive / Unarchive and Delete (admin-only, with confirmation).'], [{ q: 'Lineage edge kinds?', a: 'derived, split (fanout), selected (gate), merged.' }, { q: 'Delete removes the file?', a: 'No, only the DB rows; the .md stays.' }], [{ to: '/doc-mode', label: 'Doc mode' }, { to: '/workflows', label: 'Flows' }]),
  p('/packs', 'Industry packs', ['One click installs a team, its flows and skills.', 'Each topic is a folder in the workspace; stages advance one by one.'], ['Install a pack (existing staff are left untouched).', 'Press “Installed — see the flows” or open the stage board.', 'Create a topic and run each stage; gated stages wait in the inbox.', 'Press OK or send back with feedback.'], [{ q: 'Uninstall removes?', a: 'Only the pack’s flows; staff and folders stay.' }], [{ to: '/workflows', label: 'Flows' }, { to: '/inbox', label: 'Inbox' }]),
  p('/setup', 'Setup wizard', ['Five first-run steps: Hermes → API door → agents → admin password → done.', 'Owner only.'], ['Check Hermes is installed.', 'Open the API door (writes a key to ~/.hermes/.env and restarts the gateway).', 'Enable profiles.', 'Change the admin password.'], [{ q: '“Wrong key”?', a: 'HERMES_API_KEY differs from API_SERVER_KEY in .env; make them match and restart Studio.' }], [{ to: '/settings', label: 'Hermes status' }, { to: '/compat', label: 'Compatibility' }]),
  p('/settings', 'Settings', ['Only everyday pages stay in the sidebar; everything else (connect, cost, look and voice, system) starts here.', 'Quick prefs on top: engineer mode and theme.'], ['Turn on Engineer mode to see Session IDs, Run IDs, profile names, model ids and the Hermes status section at the bottom.', 'LINE or cron: Connect → Channels / Cron.', 'Spend: Cost → Usage / Limits.', 'A rejected gateway key shows a red banner regardless of mode.'], [{ q: 'Remote Hermes?', a: 'Set HERMES_API_URL and HERMES_API_KEY.' }], [{ to: '/channels', label: 'Channels' }, { to: '/limits', label: 'Limits' }, { to: '/theme', label: 'Theme' }]),
]
