// English skeleton of the help drawer; same paths as zh-TW
import type { HelpPage } from './types'

const p = (path: string, title: string, what: string[], how: string[], faq: { q: string; a: string }[], related: { to: string; label: string }[]): HelpPage => ({ path, title, what, how, faq, related })

export const pagesEn: HelpPage[] = [
  p('/', 'Workbench', ['Chat with one agent.', 'Sessions on the left, messages and composer on the right.'], ['Pick an agent top-left.', 'Press “+ New session”, type a task, Enter.', 'Stop or steer while streaming.', 'Approve or deny dangerous commands when asked.', 'Ctrl/⌘+K searches all sessions.'], [{ q: 'My profile is missing?', a: 'Enable it on the Agents page; only default is enabled at first.' }, { q: 'Where is history stored?', a: 'In Studio’s DB; Hermes history is under the “Hermes” group and must be imported.' }], [{ to: '/agents', label: 'Agents' }, { to: '/inbox', label: 'Inbox' }]),
  p('/agents', 'Agents', ['Each Hermes profile maps to one agent.', 'Name/title are for colleagues; SOUL.md is the persona.'], ['Enable the profile.', 'Fill name and title, save.', 'Edit SOUL.md; applies on next run.', 'Use “History” to diff and roll back.'], [{ q: 'How to add an agent?', a: 'Create a profile on the Profiles page.' }, { q: 'Shared memory?', a: 'Yes, Hermes keeps one memory per profile.' }], [{ to: '/profiles', label: 'Profiles' }, { to: '/models', label: 'Models' }]),
  p('/profiles', 'Profiles', ['A profile is an isolated Hermes identity.', 'Create, clone, delete; assign profiles to accounts.'], ['Create with a name.', 'Optionally clone an existing profile.', 'Enable it on Agents.', 'Assign to members under account binding.'], [{ q: 'Delete removes files?', a: 'Yes, ~/.hermes/profiles/<p> is removed.' }], [{ to: '/agents', label: 'Agents' }]),
  p('/models', 'Models', ['Providers discovered from Hermes config.', 'Set each profile’s default model; keys stay on the server.'], ['Pick a profile.', 'Choose a model, save.', 'Per-session override is in the chat header.'], [{ q: 'Provider missing?', a: 'Hermes has no credentials for it; run `hermes auth`.' }], [{ to: '/usage', label: 'Usage' }]),
  p('/skills', 'Skills & Memory', ['Per-profile skills, bundles, memory files, journey graph.'], ['Pick a profile.', 'Toggle skills or write notes.', 'Edit memory files; applies on next run.'], [{ q: 'Disable deletes files?', a: 'No, only flagged.' }], [{ to: '/agents', label: 'Agents' }]),
  p('/groupchat', 'Group chat', ['Two or more agents in one room; invite colleagues.', '@name picks who answers.'], ['Create a room, pick agents and policy.', 'Type “@name question”.', 'Compress when messages pile up.', 'Share the 8-char invite code.'], [{ q: 'Agents do not talk to each other?', a: 'Un-mentioned AI messages never trigger others; depth limit is 3.' }], [{ to: '/', label: 'Workbench' }]),
  p('/workflows', 'Workflows', ['Chain agents into a pipeline with gates, conditions, loops, delivery.', 'List here; canvas inside.'], ['Create or load the example.', 'Add nodes and connect.', 'Edit prompts; Ctrl/⌘+S saves.', 'Run; approve at the gate.', 'Set budget, cron, webhook under Trigger.'], [{ q: 'budget_exceeded on node 2?', a: 'max_tokens too small; start at 200000.' }, { q: 'LINE delivery fails?', a: 'Configure the LINE channel first.' }], [{ to: '/workflows/approvals', label: 'Approvals' }, { to: '/limits', label: 'Limits' }]),
  p('/workflows/approvals', 'Approvals', ['Workflows paused at a gate.'], ['Expand an item.', 'Approve with a comment or reject.'], [{ q: 'vs Inbox?', a: 'Inbox merges all decision types.' }], [{ to: '/workflows', label: 'Workflows' }]),
  p('/workflows/runs', 'Run snapshot', ['Step-by-step replay of one run.'], ['Drag the slider.', 'Click a node for its conversation.', 'Rerun from a node.'], [{ q: 'Why skipped?', a: 'Budget exceeded or condition false.' }], [{ to: '/workflows', label: 'Workflows' }]),
  p('/kanban', 'Kanban', ['Same kanban.db as `hermes kanban`.', 'Drag to move; Dispatch hands a card to Hermes.'], ['Create a card.', 'Drag between columns (not into Running).', 'Open a card and Dispatch; dry-run first.'], [{ q: 'Yellow banner?', a: '`hermes kanban diagnostics` output.' }], [{ to: '/inbox', label: 'Inbox' }]),
  p('/coding', 'Coding Agents', ['Install, configure and run Claude Code / Codex / Pi.'], ['Install if missing.', 'Configure workspace, model, API mode, budget.', 'New session, type a task, run.', 'Check the diff tab.'], [{ q: 'No budget in proxy mode?', a: 'Claude Code would misprice; omitted on purpose.' }], [{ to: '/workflows', label: 'Workflows' }]),
  p('/inbox', 'Inbox', ['Everything needing a human decision.', 'Handled items disappear.'], ['Filter by kind.', 'Approve/reject gates inline.', 'Open others, then mark done.'], [{ q: 'Count not updating?', a: 'Fetched on mount; refresh.' }], [{ to: '/workflows/approvals', label: 'Approvals' }]),
  p('/events', 'Events', ['Immutable timeline of everything that entered the hub.'], ['Filter by source/kind/agent.', 'Change the date range.', 'Export CSV.'], [{ q: 'Empty?', a: 'Widen the range or run a chat.' }], [{ to: '/inbox', label: 'Inbox' }]),
  p('/channels', 'Channels', ['Connect Hermes to LINE, Telegram, Discord, Slack.', 'Secrets go to ~/.hermes/.env only.'], ['Check gateway.', 'Fill LINE token/secret/public URL.', 'Save and restart gateway.', 'Paste webhook URL into LINE.'], [{ q: 'Public URL?', a: 'An https URL reaching port 8646, e.g. a tunnel.' }], [{ to: '/settings', label: 'Hermes status' }]),
  p('/cron', 'Cron', ['Hermes scheduled jobs via gateway.'], ['Create with a 5-field cron.', 'Pick profile, prompt, delivery.', 'Pause, resume, run now.'], [{ q: 'Timezone?', a: 'Server local time.' }], [{ to: '/workflows', label: 'Workflows' }]),
  p('/files', 'Files', ['Browse local Hermes workspace, profiles, uploads.'], ['Switch root.', 'Open folders.', 'Edit text files.', 'Attach to chat.'], [{ q: 'Docker/SSH?', a: 'Local filesystem only.' }], [{ to: '/', label: 'Workbench' }]),
  p('/usage', 'Usage', ['30-day tokens, cost and cache hit rate from Hermes state.db.'], ['Pick a range.', 'Filter to Studio-only.', 'Set price 0 for subscription models.'], [{ q: 'Differs from bill?', a: 'Estimated from a price table.' }], [{ to: '/limits', label: 'Limits' }]),
  p('/limits', 'Cost guardrails', ['Daily token/USD limits per company or agent.'], ['Pick scope.', 'Set limits.', 'Choose disable or notify.', 'Save; resets daily.'], [{ q: 'Re-enable?', a: 'On the Agents page or next day.' }], [{ to: '/usage', label: 'Usage' }]),
  p('/soul-history', 'SOUL history', ['Every SOUL.md write through Studio is versioned.'], ['Pick a profile.', 'Diff two versions.', 'Roll back.'], [{ q: 'External edits?', a: 'Not versioned.' }], [{ to: '/agents', label: 'Agents' }]),
  p('/theme', 'Theme', ['Light/dark, style, font size, colors; synced to your account.'], ['Pick a mode.', 'Adjust.', 'Reset.'], [{ q: 'Top bar toggle?', a: 'Same setting.' }], [{ to: '/settings', label: 'Hermes status' }]),
  p('/logs', 'Logs', ['Hermes, profile and Studio logs with filters and follow.'], ['Pick a file.', 'Filter.', 'Follow.'], [{ q: 'Which first?', a: 'Gateway log for chat issues; Studio log for 500s.' }], [{ to: '/events', label: 'Events' }]),
  p('/voice', 'Voice', ['Browser speech first; whisper.cpp / edge-tts fallback.'], ['Test mic.', 'Test TTS.', 'Install fallbacks if needed.'], [{ q: 'edge-tts not bundled?', a: 'GPL-3.0.' }], [{ to: '/groupchat', label: 'Group chat' }]),
  p('/admin', 'Admin', ['Terminal, MCP servers, plugins, versions.'], ['Terminal tab.', 'MCP tab.', 'Plugins tab.', 'Version tab.'], [{ q: 'First login?', a: 'Change the admin password.' }], [{ to: '/settings', label: 'Hermes status' }]),
  p('/search', 'Search', ['One box searches chats, group rooms, workflow outputs and events (FTS5, CJK aware).'], ['Type a keyword.', 'Narrow by scope, time or agent.', 'Give agents the same search: `myhermescompany install-skill mhc-search --profile <p>`.'], [{ q: 'Fresh message missing?', a: 'The index syncs every few seconds.' }], [{ to: '/events', label: 'Events' }]),
  p('/compat', 'Hermes compatibility', ['Every Hermes touch point is a contract item checked against the real Hermes.', 'Verdict: compatible / partial / incompatible, with affected modules.'], ['Run “Check now” (read-only, ~1 min).', 'Before upgrading, run “Precheck” for a version: sandbox install, never touches ~/.hermes.', 'CLI: `myhermescompany hermes-check`, `myhermescompany precheck <tag>`.'], [{ q: 'Is “partial” usable?', a: 'Yes; only critical failures mean incompatible.' }], [{ to: '/settings', label: 'Hermes status' }]),
  p('/packs', 'Industry packs', ['A pack bundles agents, per-stage workflows, skills and stage definitions.', 'Each topic is a folder in the workspace; stages advance one by one.'], ['Install a pack (existing profiles are left untouched).', 'Create a topic.', 'Run each stage; gated stages wait in the inbox.', 'Approve or send back with feedback.'], [{ q: 'Uninstall removes?', a: 'Only the pack’s workflows; agents, profiles and folders stay.' }], [{ to: '/workflows', label: 'Workflows' }, { to: '/inbox', label: 'Inbox' }]),
  p('/setup', 'Setup wizard', ['Five first-run steps: Hermes → API door → agents → admin password → done.', 'Owner only.'], ['Check Hermes is installed.', 'Open the API door (writes a key to ~/.hermes/.env and restarts the gateway).', 'Enable profiles.', 'Change the admin password.'], [{ q: '“Wrong key”?', a: 'HERMES_API_KEY differs from API_SERVER_KEY in .env; make them match and restart Studio.' }], [{ to: '/settings', label: 'Hermes status' }, { to: '/compat', label: 'Compatibility' }]),
  p('/settings', 'Hermes status', ['Gateway reachability, version, profiles.'], ['If gateway is down, check ~/.hermes/.env and restart.', 'Refresh.'], [{ q: 'Remote Hermes?', a: 'Set HERMES_API_URL and HERMES_API_KEY.' }], [{ to: '/channels', label: 'Channels' }]),
]
